
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 7;
  public static final int INT = 11;
  public static final int SEMI = 10;
  public static final int EOF = 0;
  public static final int PLUS = 6;
  public static final int TYINT = 3;
  public static final int ID = 13;
  public static final int DIV = 9;
  public static final int ASSIGN = 5;
  public static final int error = 1;
  public static final int TYFLOAT = 2;
  public static final int PRINT = 4;
  public static final int TIMES = 8;
  public static final int FLOAT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TYFLOAT",
  "TYINT",
  "PRINT",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "SEMI",
  "INT",
  "FLOAT",
  "ID"
  };
}

